name: build

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JAVA_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'sbt'

      - name: Setup sbt
        uses: sbt/setup-sbt@8feba82adc7f01ddcf8165b86f778bdb5b82cebc # v1.5.7

      - name: Test
        run: |
          sbt "headerCheckAll;" \
            "scalafmtSbtCheck;" \
            "scalafmtCheckAll;" \
            "scalafixAll --check;" \
            "testFull;" \
            "+publishLocal;" \
            "scripted"
        # +publishLocal is now mandatory because we test (scripted) both sbt 1 and sbt 2 versions
